/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-04-21 04:14:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.common.model.vo.SubNav;

public final class myPageNavbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.common.model.vo.SubNav");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	SubNav sn = new SubNav("1", "2", "3", "4", "5", "6", "7", "8", "9");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("        /* MY PAGE 타이틀 부분 */\r\n");
      out.write("        #container .title {\r\n");
      out.write("        padding-top: 80px;\r\n");
      out.write("        height: 200px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        min-width: 1000px;\r\n");
      out.write("      }\r\n");
      out.write("      #container .sub_title {\r\n");
      out.write("        font-size: 44px;\r\n");
      out.write("        line-height: 54px;\r\n");
      out.write("        color: #000;\r\n");
      out.write("        margin-bottom: 0px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("      }\r\n");
      out.write("      h2 {\r\n");
      out.write("        margin:0;\r\n");
      out.write("        font-weight: normal;\r\n");
      out.write("        display: block;\r\n");
      out.write("      }\r\n");
      out.write("      #mini_title {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-bottom: 44px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 134px;\r\n");
      out.write("        left: 0;\r\n");
      out.write("      }\r\n");
      out.write("      ol {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        display: block;\r\n");
      out.write("      }\r\n");
      out.write("      li {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        list-style: none;\r\n");
      out.write("\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("      }\r\n");
      out.write("      a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: #000;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      /* 메뉴바 부분 */\r\n");
      out.write("      #mnb {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        min-width: 1000px;\r\n");
      out.write("        border-bottom: 1px solid #888686;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        margin-bottom: 60px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #mnb .mnb_header {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        min-width: 1000px;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        border-top: 1px solid #9d9d9d;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #mnb .mnb_header>ul {\r\n");
      out.write("        width: 1000px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        display: block;\r\n");
      out.write("        list-style-type: disc;\r\n");
      out.write("      }\r\n");
      out.write("      #mnb_sub ul {\r\n");
      out.write("        width: 250px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        display: block;\r\n");
      out.write("        list-style-type: disc;\r\n");
      out.write("      }\r\n");
      out.write("      .menubar { height : 38px; }\r\n");
      out.write("\r\n");
      out.write("      #mnb.menubar .mnb_header ul li {\r\n");
      out.write("        /* width: 25%; ------------------------- */ \r\n");
      out.write("      }\r\n");
      out.write("      #mnb .mnb_header ul li {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        /* float: left; */\r\n");
      out.write("        position: relative;\r\n");
      out.write("      }\r\n");
      out.write("      b .mnb_header ul li a {\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("    /* 서브 메뉴바 부분 */\r\n");
      out.write("    #mnb_sub {\r\n");
      out.write("            list-style-type : none;\r\n");
      out.write("            /*\r\n");
      out.write("                p 태그와 마찬가지로 ul 태그 또한 위, 아래로 기본 margin 이 잡혀있음\r\n");
      out.write("                또한 ul 태그는 padding 이 왼쪽에 기본적으로 존재함\r\n");
      out.write("                => margin : 0px; 과 padding : 0px; 으로 margin 과 padding 을 없애기\r\n");
      out.write("            */\r\n");
      out.write("            /*\r\n");
      out.write("            margin : 0px;\r\n");
      out.write("            padding : 0px; /* padding 값 조정으로 메뉴 가운데 배치 가능 */\r\n");
      out.write("           /* height : 100%; */\r\n");
      out.write("\r\n");
      out.write("            width: 25%;\r\n");
      out.write("            height : 36px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 메인 메뉴를 나타내는 li 태그들 */\r\n");
      out.write("        #mnb_sub>li {\r\n");
      out.write("            float : left;\r\n");
      out.write("            height : 100%;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 메뉴 문구를 나타내는 a 태그들 */\r\n");
      out.write("        #mnb a {\r\n");
      out.write("            \r\n");
      out.write("            color : black;\r\n");
      out.write("            text-decoration : none;\r\n");
      out.write("            font-size : 14px;\r\n");
      out.write("            /*\r\n");
      out.write("                a 태그는 인라인요소이기 때문에\r\n");
      out.write("                width, height 속성이 적용되지 않음\r\n");
      out.write("                => display : block; 으로 블럭요소화 시켜줄것임\r\n");
      out.write("            */\r\n");
      out.write("            width : 250px;\r\n");
      out.write("            height : 100%;\r\n");
      out.write("            display : block;\r\n");
      out.write("            text-align : center;\r\n");
      out.write("            /* vertical-align : middle; vertical-align 은 블럭요소에서 적용되지 않음 */\r\n");
      out.write("            line-height : 36px;\r\n");
      out.write("            /*\r\n");
      out.write("                line-height 속성은 블럭요소에 대한 장평조절 속성\r\n");
      out.write("                보통은 블럭요소의 세로길이만큼 주면 알아서 가운데로 옴\r\n");
      out.write("            */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 메뉴에 마우스가 올라갔을 때 추가적인 속성 */\r\n");
      out.write("        #mnb_sub a:hover {\r\n");
      out.write("            color: #888686;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 서브메뉴에 해당되는 ul 에 대한 스타일 */\r\n");
      out.write("        #mnb_sub>li>ul {\r\n");
      out.write("            list-style-type : none;\r\n");
      out.write("            padding : 0px;\r\n");
      out.write("            display : none !important; /* 평소에는 안보여지게끔 숨김 처리 */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 메인 메뉴에 마우스가 올라가는 순간 서브메뉴가 보여지게끔 스타일 부여 */\r\n");
      out.write("        #mnb_sub>li:hover>ul {\r\n");
      out.write("            display : block !important;\r\n");
      out.write("        }\r\n");
      out.write("        /* 혹시 몰라서 서브메뉴 자체에도 효과 부여 */\r\n");
      out.write("        #mnb_sub>li>ul:hover {\r\n");
      out.write("            display : block !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #mnb .mnb_header ul li.active {\r\n");
      out.write("        background-color: #000;\r\n");
      out.write("      }\r\n");
      out.write("      #mnb .mnb_header ul li.active a {\r\n");
      out.write("        background-color: #000;\r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("      }\r\n");
      out.write("</style>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.4.js\" integrity=\"sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	");

		
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<section id=\"container\">\r\n");
      out.write("        <div class=\"title\">\r\n");
      out.write("          <h2 class=\"sub_title\">\r\n");
      out.write("            <span>");
      out.print( sn.getTitle1() );
      out.write("</span>\r\n");
      out.write("            </h2>\r\n");
      out.write("            <ol id=\"mini_title\">\r\n");
      out.write("            <li><a href=\"Daknawa\">Home</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>></li>\r\n");
      out.write("            <li><a id=\"title1\">가가</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>></li>\r\n");
      out.write("            <li><a href=\"Daknawa/");
      out.print( sn.getTitle2Addr() );
      out.write('"');
      out.write('>');
      out.print( sn.getTitle2() );
      out.write("</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>></li>\r\n");
      out.write("            <li>");
      out.print( sn.getTitle3() );
      out.write("</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"mnb\" class=\"menubar\">\r\n");
      out.write("		    <div class=\"mnb_header\">\r\n");
      out.write("		        <ul id=\"mnb_sub\">\r\n");
      out.write("	            	<li class=\"");
      out.print( sn.getActive1() );
      out.write("\">\r\n");
      out.write("	                    <a href=\"Daknawa/myInfo.me\">내 정보 관리</a>\r\n");
      out.write("	                    <ul>\r\n");
      out.write("	                        <li style=\"display: block !important;\"><a href=\"Daknawa/myInfo.me\">정보 조회 및 수정</a></li>\r\n");
      out.write("	                        <li style=\"display: block !important;\"><a href=\"Daknawa/deleteForm.me\">탈퇴</a></li>                   \r\n");
      out.write("	                    </ul>\r\n");
      out.write("	                </li>\r\n");
      out.write("	                <li class=\"");
      out.print( sn.getActive2() );
      out.write("\">\r\n");
      out.write("	                    <a href=\"\">내 활동 관리</a>\r\n");
      out.write("	                    <ul>\r\n");
      out.write("	                        <li><a href=\"\">게시글 관리</a></li>\r\n");
      out.write("	                        <li><a href=\"\">댓글 관리</a></li>\r\n");
      out.write("	                        <li><a href=\"\">좋아요 관리</a></li>                   \r\n");
      out.write("	                    </ul>\r\n");
      out.write("	                </li>\r\n");
      out.write("	                <li class=\"");
      out.print( sn.getActive3() );
      out.write("\">\r\n");
      out.write("	                    <a href=\"\">내 신고 관리</a>\r\n");
      out.write("	                    <ul>\r\n");
      out.write("	                        <li><a href=\"\">A</a></li>\r\n");
      out.write("	                        <li><a href=\"\">B</a></li>\r\n");
      out.write("	                        <li><a href=\"\">C</a></li>                   \r\n");
      out.write("	                    </ul>\r\n");
      out.write("	                </li>\r\n");
      out.write("	                <li class=\"");
      out.print( sn.getActive4() );
      out.write("\">\r\n");
      out.write("	                    <a href=\"Daknawa/list.ask\">문의내역</a>\r\n");
      out.write("	                    <ul>\r\n");
      out.write("	                        <li><a href=\"Daknawa/list.ask\">1:1문의내역관리</a></li>\r\n");
      out.write("	                        <li><a href=\"Daknawa/faq.qna\">FAQ</a></li>\r\n");
      out.write("	                        <li><a href=\"\">C</a></li>                \r\n");
      out.write("	                    </ul>\r\n");
      out.write("	                </li>\r\n");
      out.write("		        </ul>\r\n");
      out.write("		    </div>\r\n");
      out.write("		    <br>\r\n");
      out.write("    	</div>\r\n");
      out.write("    	\r\n");
      out.write("    </section>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("		  $(\"a\").click(function(){\r\n");
      out.write("		    console.log($(this).text());\r\n");
      out.write("		  });\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.4.js\" integrity=\"sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
