/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-04-23 09:29:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.kh.post.model.vo.Post;
import com.kh.member.model.vo.Member;
import com.kh.common.model.vo.SubNav;

public final class adminTable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/admin/../common/menubar.jsp", Long.valueOf(1682241112684L));
    _jspx_dependants.put("/views/admin/../common/adminPageNavbar.jsp", Long.valueOf(1682241112684L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.common.model.vo.SubNav");
    _jspx_imports_classes.add("com.kh.post.model.vo.Post");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    ArrayList<Post> list = (ArrayList<Post>)request.getAttribute("list");

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Data Table | Notika - Notika Admin Template</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- favicon\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"resources/admin/image/x-icon\" href=\"resources/admin/img/favicon.ico\">\r\n");
      out.write("    <!-- Google Fonts\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Bootstrap CSS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/admin/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- font awesome CSS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/admin/css/font-awesome.min.css\">\r\n");
      out.write("  \r\n");
      out.write("    <!-- meanmenu CSS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/admin/css/meanmenu/meanmenu.min.css\">\r\n");
      out.write("    <!-- animate CSS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/admin/css/animate.css\">\r\n");
      out.write("    <!-- normalize CSS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/admin/css/normalize.css\">\r\n");
      out.write("	<!-- wave CSS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/admin/css/wave/waves.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/admin/css/wave/button.css\">\r\n");
      out.write("    <!-- mCustomScrollbar CSS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/admin/css/scrollbar/jquery.mCustomScrollbar.min.css\">\r\n");
      out.write("    <!-- Notika icon CSS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/admin/css/notika-custom-icon.css\">\r\n");
      out.write("    <!-- Data Table JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/admin/css/jquery.dataTables.min.css\">\r\n");
      out.write("    <!-- main CSS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/admin/css/main.css\">\r\n");
      out.write("    <!-- style CSS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/admin/style.css\">\r\n");
      out.write("    <!-- responsive CSS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/admin/css/responsive.css\">\r\n");
      out.write("    <!-- modernizr JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/vendor/modernizr-2.8.3.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');

	
	String contextPath = request.getContextPath(); // "/jsp"
	
	Member loginUser = (Member)session.getAttribute("loginUser"); // 로그인한 유저의 정보
	
	String alertMsg = (String)session.getAttribute("alertMsg"); // alert 메세지
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"english\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>exported project</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta property=\"twitter:card\" content=\"summary_large_image\" />\r\n");
      out.write("<!-- 스타일을 위한 연동 구문 (외부 스타일 방식) -->\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 기본 동적인 효과를 위한 연동 구문 (외부 js 방식) => 순서 주의!! -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script> <!-- 온라인 방식 -->\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- CSS only -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\"\r\n");
      out.write("	crossorigin=\"anonymous\" />\r\n");
      out.write("	<!-- 기본 동적인 효과를 위한 연동 구문 (외부 js 방식) => 순서 주의!! -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script> <!-- 온라인 방식 -->\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<style data-tag=\"reset-style-sheet\">\r\n");
      out.write("html {\r\n");
      out.write("	line-height: 1.15;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	border-width: 0;\r\n");
      out.write("	border-style: solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p, li, ul, pre, div, h1, h2, h3, h4, h5, h6, figure, blockquote,\r\n");
      out.write("	figcaption {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("	background-color: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button, input, optgroup, select, textarea {\r\n");
      out.write("	font-family: inherit;\r\n");
      out.write("	font-size: 100%;\r\n");
      out.write("	line-height: 1.15;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button, select {\r\n");
      out.write("	text-transform: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button, [type=\"button\"], [type=\"reset\"], [type=\"submit\"] {\r\n");
      out.write("	-webkit-appearance: button;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button::-moz-focus-inner, [type=\"button\"]::-moz-focus-inner, [type=\"reset\"]::-moz-focus-inner,\r\n");
      out.write("	[type=\"submit\"]::-moz-focus-inner {\r\n");
      out.write("	border-style: none;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:-moz-focus, [type=\"button\"]:-moz-focus, [type=\"reset\"]:-moz-focus,\r\n");
      out.write("	[type=\"submit\"]:-moz-focus {\r\n");
      out.write("	outline: 1px dotted ButtonText;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	color: inherit;\r\n");
      out.write("	text-decoration: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("	padding: 2px 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("	scroll-behavior: smooth;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<style data-tag=\"default-style-sheet\">\r\n");
      out.write("html {\r\n");
      out.write("	font-family: Inter;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	text-transform: none;\r\n");
      out.write("	letter-spacing: normal;\r\n");
      out.write("	line-height: 1.15;\r\n");
      out.write("	color: var(- -dl-color-gray-black);\r\n");
      out.write("	background-color: var(- -dl-color-gray-white);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-box1 {\r\n");
      out.write("	background-color: #f9f9f9;\r\n");
      out.write("	min-width: 160px;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	height: 80px;\r\n");
      out.write("	border: 1px solid #f9f9f9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div {\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("/* navigator 에 대한 작업용 임시스타일 */\r\n");
      out.write("#navigator {\r\n");
      out.write("	width: 1000px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 전체를 감사는 navi */\r\n");
      out.write("#navi {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	/*\r\n");
      out.write("            p 태그와 마찬가지로 ul 태그 또한 위, 아래로 기본 margin 이 잡혀있음\r\n");
      out.write("            또한 ul 태그는 padding이 왼쪽에 기본적으로 존재함\r\n");
      out.write("            => margin : 0px; 과 padding : 0px; 으로 margin과 padding을 없애기\r\n");
      out.write("        */\r\n");
      out.write("	margin: 0px;\r\n");
      out.write("	padding: 0px; /* padding 값 조정으로 메뉴 가운데 배치 가능 */\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 메인 메뉴 나타내는 li 태그들 */\r\n");
      out.write("#navi>li {\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 15%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 메뉴 문구를 나타내는 a 태그들 */\r\n");
      out.write("#navi a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: lightcoral;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	font-weight: 900;\r\n");
      out.write("	/*\r\n");
      out.write("                a 태그는 인라인요소이기 때문에\r\n");
      out.write("                width, height 속성이 적용되지 않음\r\n");
      out.write("                => display : block;으로 블럭요소화 시켜줄것임\r\n");
      out.write("            */\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	/*vertical-align : middle;*/ /* verical-align 은 블럭요소에서 적용되지 않음 */\r\n");
      out.write("	line-height: 35px;\r\n");
      out.write("	/*\r\n");
      out.write("                line_height 속성은 블럭요소에 대한 장편조절 속성\r\n");
      out.write("                보통은 블럭요소의 세로길이만큼 주면 알아서 가운데로 옴\r\n");
      out.write("            */\r\n");
      out.write("}\r\n");
      out.write("/* 메뉴에 마우스가 올라갔을 때 추가적인 속성 */\r\n");
      out.write("#navi a:hover {\r\n");
      out.write("	color: crimson;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 서브메뉴에 해당되는 ul에 대한 스타일 */\r\n");
      out.write("#navi>li>ul {\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	padding: 0px;\r\n");
      out.write("	display: none; /* 평소에는 안보여지게끔 숨김 처리 */\r\n");
      out.write("}\r\n");
      out.write("/* 메인 메뉴에 마우스가 올라가는 순간 서브메뉴가 보여지게끔 스타일 부여*/\r\n");
      out.write("#navi>li:hover>ul {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 혹시 몰라서 서브메뉴 자체에도 효과 부여 */\r\n");
      out.write("#navi>li>ul:hover {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 추가적으로 글씨 크기조정, 스타일, ... */\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap\"\r\n");
      out.write("	data-tag=\"font\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap\"\r\n");
      out.write("	data-tag=\"font\" />\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"./style.css\" /> -->\r\n");
      out.write("<link href=\"resources/css/navbar11.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/ba6f730a41.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div>\r\n");
      out.write("		<div class=\"navbar11-navbar1\">\r\n");
      out.write("			<div class=\"navbar11-container1\">\r\n");
      out.write("				<img onclick=\"location.href='");
      out.print( contextPath );
      out.write("'\" style=\"cursor: pointer\"\r\n");
      out.write("					src=\"resources/css/logoimg+logoname.png\" alt=\"logoI204\"\r\n");
      out.write("					class=\"navbar11-logo\" />\r\n");
      out.write("				<div class=\"navbar11-column1\">\r\n");
      out.write("					<div class=\"navbar11-column2\">\r\n");
      out.write("						<span \r\n");
      out.write("							class=\"navbar11-text TextRegularNormal\" style=\"cursor: pointer\">\r\n");
      out.write("							<div class=\"dropdown\">\r\n");
      out.write("								<button class=\"btn btn-secondary dropdown-toggle\"\r\n");
      out.write("									style=\"background-color: rgba(64, 81, 59, 1); border: 0px; border-radius: 0px;\"\r\n");
      out.write("									type=\"button\" id=\"dropdownMenuButton1\"\r\n");
      out.write("									data-bs-toggle=\"dropdown\" aria-expanded=\"false\">게시판</button>\r\n");
      out.write("								<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton1\">\r\n");
      out.write("									<li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/plist.bo?currentPage=1\">자유 게시판</a></li>\r\n");
      out.write("									<li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/review.bo?currentPage=1\">사진 게시판1</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</span>\r\n");
      out.write("						<div class=\"dropdown\">\r\n");
      out.write("							<button class=\"btn btn-secondary\"\r\n");
      out.write("								onclick=\"location.href='");
      out.print( contextPath );
      out.write("/menu.mn'\"\r\n");
      out.write("								style=\"background-color: rgba(64, 81, 59, 1); border: 0px; border-radius: 0px;\"\r\n");
      out.write("								type=\"button\" id=\"dropdownMenuButton1\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("								aria-expanded=\"false\">메뉴 정보</button>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dropdown\">\r\n");
      out.write("							<button class=\"btn btn-secondary\"\r\n");
      out.write("								onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.st?currentPage=1'\"\r\n");
      out.write("								style=\"background-color: rgba(64, 81, 59, 1); border: 0px; border-radius: 0px;\"\r\n");
      out.write("								type=\"button\" id=\"dropdownMenuButton1\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("								aria-expanded=\"false\">매장 정보</button>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"dropdown\">\r\n");
      out.write("							<button class=\"btn btn-secondary dropdown-toggle\"\r\n");
      out.write("								style=\"background-color: rgba(64, 81, 59, 1); border: 0px; border-radius: 0px;\"\r\n");
      out.write("								type=\"button\" id=\"dropdownMenuButton1\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("								aria-expanded=\"false\">더보기</button>\r\n");
      out.write("							<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton1\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/myPage.me\">마이 페이지</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">문의 하기</a></li>\r\n");
      out.write("\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					");
 if(loginUser == null) { // 로그인 하기 전  
      out.write("\r\n");
      out.write("						<div class=\"navbar11-column3\">\r\n");
      out.write("							<button onclick=\"location.href='");
      out.print( contextPath );
      out.write("/loginPage.me'\"\r\n");
      out.write("								class=\"navbar11-button\" style=\"cursor: pointer\">\r\n");
      out.write("								<span class=\"navbar11-text08 TextRegularNormal\"> <span>로그인</span>\r\n");
      out.write("								</span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					");
 } else { // 로그인 한 후 
      out.write("\r\n");
      out.write("						<div class=\"navbar11-column3\">\r\n");
      out.write("							<button onclick=\"location.href='");
      out.print( contextPath );
      out.write("/logout.me'\"\r\n");
      out.write("								class=\"navbar11-button\" style=\"cursor: pointer\">\r\n");
      out.write("								<span class=\"navbar11-text08 TextRegularNormal\"> <span>로그아웃</span>\r\n");
      out.write("								</span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- alert 스크립트 -->\r\n");
      out.write("	<script>\r\n");
      out.write("		let msg = \"");
      out.print( alertMsg );
      out.write("\";\r\n");
      out.write("		\r\n");
      out.write("		if(msg != \"null\") {\r\n");
      out.write("			alert(msg);\r\n");
      out.write("			");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("		\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');

	SubNav sn = (SubNav)request.getAttribute("sn");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("        /* MY PAGE 타이틀 부분 */\r\n");
      out.write("        #container .title {\r\n");
      out.write("        padding-top: 80px;\r\n");
      out.write("        height: 200px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        min-width: 1000px;\r\n");
      out.write("      }\r\n");
      out.write("      #container .sub_title {\r\n");
      out.write("        font-size: 44px;\r\n");
      out.write("        line-height: 54px;\r\n");
      out.write("        color: #000;\r\n");
      out.write("        margin-bottom: 0px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("      }\r\n");
      out.write("      h2 {\r\n");
      out.write("        margin:0;\r\n");
      out.write("        font-weight: normal;\r\n");
      out.write("        display: block;\r\n");
      out.write("      }\r\n");
      out.write("      #mini_title {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-bottom: 44px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 134px;\r\n");
      out.write("        left: 0;\r\n");
      out.write("      }\r\n");
      out.write("      ol {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        display: block;\r\n");
      out.write("      }\r\n");
      out.write("      li {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        list-style: none;\r\n");
      out.write("\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("      }\r\n");
      out.write("      a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: #000;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      /* 메뉴바 부분 */\r\n");
      out.write("      #mnb {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        min-width: 1000px;\r\n");
      out.write("        border-bottom: 1px solid #888686;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        margin-bottom: 60px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #mnb .mnb_header {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        min-width: 1000px;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        border-top: 1px solid #9d9d9d;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #mnb .mnb_header>ul {\r\n");
      out.write("        width: 1000px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        display: block;\r\n");
      out.write("        list-style-type: disc;\r\n");
      out.write("      }\r\n");
      out.write("      #mnb_sub ul {\r\n");
      out.write("        width: 250px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        display: block;\r\n");
      out.write("        list-style-type: disc;\r\n");
      out.write("      }\r\n");
      out.write("      .menubar { height : 38px; }\r\n");
      out.write("\r\n");
      out.write("      #mnb.menubar .mnb_header ul li {\r\n");
      out.write("        /* width: 25%; ------------------------- */ \r\n");
      out.write("      }\r\n");
      out.write("      #mnb .mnb_header ul li {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        /* float: left; */\r\n");
      out.write("        position: relative;\r\n");
      out.write("      }\r\n");
      out.write("      b .mnb_header ul li a {\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("    /* 서브 메뉴바 부분 */\r\n");
      out.write("    #mnb_sub {\r\n");
      out.write("            list-style-type : none;\r\n");
      out.write("            /*\r\n");
      out.write("                p 태그와 마찬가지로 ul 태그 또한 위, 아래로 기본 margin 이 잡혀있음\r\n");
      out.write("                또한 ul 태그는 padding 이 왼쪽에 기본적으로 존재함\r\n");
      out.write("                => margin : 0px; 과 padding : 0px; 으로 margin 과 padding 을 없애기\r\n");
      out.write("            */\r\n");
      out.write("            /*\r\n");
      out.write("            margin : 0px;\r\n");
      out.write("            padding : 0px; /* padding 값 조정으로 메뉴 가운데 배치 가능 */\r\n");
      out.write("           /* height : 100%; */\r\n");
      out.write("\r\n");
      out.write("            width: 25%;\r\n");
      out.write("            height : 36px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 메인 메뉴를 나타내는 li 태그들 */\r\n");
      out.write("        #mnb_sub>li {\r\n");
      out.write("            float : left;\r\n");
      out.write("            height : 100%;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 메뉴 문구를 나타내는 a 태그들 */\r\n");
      out.write("        #mnb a {\r\n");
      out.write("            \r\n");
      out.write("            color : black;\r\n");
      out.write("            text-decoration : none;\r\n");
      out.write("            font-size : 14px;\r\n");
      out.write("            /*\r\n");
      out.write("                a 태그는 인라인요소이기 때문에\r\n");
      out.write("                width, height 속성이 적용되지 않음\r\n");
      out.write("                => display : block; 으로 블럭요소화 시켜줄것임\r\n");
      out.write("            */\r\n");
      out.write("            width : 250px;\r\n");
      out.write("            height : 100%;\r\n");
      out.write("            display : block;\r\n");
      out.write("            text-align : center;\r\n");
      out.write("            /* vertical-align : middle; vertical-align 은 블럭요소에서 적용되지 않음 */\r\n");
      out.write("            line-height : 36px;\r\n");
      out.write("            /*\r\n");
      out.write("                line-height 속성은 블럭요소에 대한 장평조절 속성\r\n");
      out.write("                보통은 블럭요소의 세로길이만큼 주면 알아서 가운데로 옴\r\n");
      out.write("            */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 메뉴에 마우스가 올라갔을 때 추가적인 속성 */\r\n");
      out.write("        #mnb_sub a:hover {\r\n");
      out.write("            color: #888686;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 서브메뉴에 해당되는 ul 에 대한 스타일 */\r\n");
      out.write("        #mnb_sub>li>ul {\r\n");
      out.write("            list-style-type : none;\r\n");
      out.write("            padding : 0px;\r\n");
      out.write("            display : none !important; /* 평소에는 안보여지게끔 숨김 처리 */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 메인 메뉴에 마우스가 올라가는 순간 서브메뉴가 보여지게끔 스타일 부여 */\r\n");
      out.write("        #mnb_sub>li:hover>ul {\r\n");
      out.write("            display : block !important;\r\n");
      out.write("        }\r\n");
      out.write("        /* 혹시 몰라서 서브메뉴 자체에도 효과 부여 */\r\n");
      out.write("        #mnb_sub>li>ul:hover {\r\n");
      out.write("            display : block !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #mnb .mnb_header ul li.active {\r\n");
      out.write("        background-color: #000;\r\n");
      out.write("      }\r\n");
      out.write("      #mnb .mnb_header ul li.active a {\r\n");
      out.write("        background-color: #000;\r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("      }\r\n");
      out.write("</style>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.4.js\" integrity=\"sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<section id=\"container\">\r\n");
      out.write("        <div class=\"title\">\r\n");
      out.write("          <h2 class=\"sub_title\">\r\n");
      out.write("            <span>");
      out.print( sn.getTitle1() );
      out.write("</span>\r\n");
      out.write("            </h2>\r\n");
      out.write("            <ol id=\"mini_title\">\r\n");
      out.write("            <li><a href=\"/Daknawa\">Home</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>></li>\r\n");
      out.write("            <li><a id=\"title1\" href=\"");
      out.print( sn.getTitle1Addr() );
      out.write('"');
      out.write('>');
      out.print( sn.getTitle1() );
      out.write("</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( sn.getTitle2Addr() );
      out.write('"');
      out.write('>');
      out.print( sn.getTitle2() );
      out.write("</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>></li>\r\n");
      out.write("            <li>");
      out.print( sn.getTitle3() );
      out.write("</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- ---------------------------------------- -->\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"mnb\" class=\"menubar\">\r\n");
      out.write("		    <div class=\"mnb_header\">\r\n");
      out.write("		        <ul id=\"mnb_sub\">\r\n");
      out.write("	            	<li class=\"");
      out.print( sn.getActive1() );
      out.write("\">\r\n");
      out.write("	                    <a href=\"list.me?currentPage=1\">회원 관리</a>\r\n");
      out.write("	                    <ul>\r\n");
      out.write("	                        <li style=\"display: block !important;\"><a href=\"list.me?currentPage=1\">회원정보 조회</a></li>\r\n");
      out.write("	                        <li style=\"display: block !important;\"><a href=\"admin.me\">회원 탈퇴</a></li>                   \r\n");
      out.write("	                    </ul>\r\n");
      out.write("	                </li>\r\n");
      out.write("	                <li class=\"");
      out.print( sn.getActive2() );
      out.write("\">\r\n");
      out.write("	                    <a href=\"adlist.st?currentPage=1\">매장 관리</a>\r\n");
      out.write("	                    <ul>\r\n");
      out.write("	                        <li><a href=\"adlist.st?currentPage=1\">전체 매장 조회</a></li>\r\n");
      out.write("	                        <li><a href=\"adlist.st?currentPage=1\">???</a></li>\r\n");
      out.write("	                        <li><a href=\"adlist.st?currentPage=1\">???</a></li>                   \r\n");
      out.write("	                    </ul>\r\n");
      out.write("	                </li>\r\n");
      out.write("	                <li class=\"");
      out.print( sn.getActive3() );
      out.write("\">\r\n");
      out.write("	                    <a href=\"\">신고내역 관리</a>\r\n");
      out.write("	                    <ul>\r\n");
      out.write("	                        <li><a href=\"table.ad\">전체 신고내역 조회</a></li>\r\n");
      out.write("	                        <li><a href=\"\">???</a></li>\r\n");
      out.write("	                        <li><a href=\"\">???</a></li>                   \r\n");
      out.write("	                    </ul>\r\n");
      out.write("	                </li>\r\n");
      out.write("	                <li class=\"");
      out.print( sn.getActive4() );
      out.write("\">\r\n");
      out.write("	                    <a href=\"list.ask\">문의내역 관리</a>\r\n");
      out.write("	                    <ul>\r\n");
      out.write("	                        <li><a href=\"list.ask\">1:1 문의내역 관리</a></li>\r\n");
      out.write("	                        <li><a href=\"faq.qna\">FAQ</a></li>\r\n");
      out.write("	                        <li><a href=\"\">C</a></li>                \r\n");
      out.write("	                    </ul>\r\n");
      out.write("	                </li>\r\n");
      out.write("		        </ul>\r\n");
      out.write("		    </div>\r\n");
      out.write("		    <br>\r\n");
      out.write("    	</div>\r\n");
      out.write("    	\r\n");
      out.write("    </section>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("		  $(\"a\").click(function(){\r\n");
      out.write("		    console.log($(this).text());\r\n");
      out.write("		  });\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.4.js\" integrity=\"sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"data-table-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                    <div class=\"data-table-list\">\r\n");
      out.write("                        <div class=\"basic-tb-hd\">\r\n");
      out.write("                            <h2>게시글 관리 테이블</h2>\r\n");
      out.write("                            <p>공지, 자유, 사진 게시판 관리</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"table-responsive\">\r\n");
      out.write("                            <table id=\"data-table-basic\" class=\"table table-striped\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th>글번호</th>\r\n");
      out.write("                                        <th>닉네임</th>\r\n");
      out.write("                                        <th>글제목</th>\r\n");
      out.write("                                        <th>Age</th>\r\n");
      out.write("                                        <th>Start date</th>\r\n");
      out.write("                                        <th>Salary</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                \r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                    ");
 for(Post p : list) { 
      out.write("\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>");
      out.print( p.getPostNo() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( p.getMemberNickname() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( p.getPostTitle() );
      out.write("</td>\r\n");
      out.write("                                        <td></td>\r\n");
      out.write("                                        <td>수정</td>\r\n");
      out.write("                                        <td>삭제</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                               \r\n");
      out.write("                                <tfoot>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th>Name</th>\r\n");
      out.write("                                        <th>Position</th>\r\n");
      out.write("                                        <th>Office</th>\r\n");
      out.write("                                        <th>Age</th>\r\n");
      out.write("                                        <th>Start date</th>\r\n");
      out.write("                                        <th>Salary</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </tfoot>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Footer area-->\r\n");
      out.write("    <!-- jquery\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("    <!-- bootstrap JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- wow JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/wow.min.js\"></script>\r\n");
      out.write("    <!-- price-slider JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/jquery-price-slider.js\"></script>\r\n");
      out.write("    <!-- owl.carousel JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <!-- scrollUp JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("    <!-- meanmenu JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/meanmenu/jquery.meanmenu.js\"></script>\r\n");
      out.write("    <!-- counterup JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/counterup/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/admin/js/counterup/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/admin/js/counterup/counterup-active.js\"></script>\r\n");
      out.write("    <!-- mCustomScrollbar JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/scrollbar/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("    <!-- sparkline JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/sparkline/jquery.sparkline.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/admin/js/sparkline/sparkline-active.js\"></script>\r\n");
      out.write("    <!-- flot JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/flot/jquery.flot.js\"></script>\r\n");
      out.write("    <script src=\"resources/admin/js/flot/jquery.flot.resize.js\"></script>\r\n");
      out.write("    <script src=\"resources/admin/js/flot/flot-active.js\"></script>\r\n");
      out.write("    <!-- knob JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/knob/jquery.knob.js\"></script>\r\n");
      out.write("    <script src=\"resources/admin/js/knob/jquery.appear.js\"></script>\r\n");
      out.write("    <script src=\"resources/admin/js/knob/knob-active.js\"></script>\r\n");
      out.write("    <!--  Chat JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/chat/jquery.chat.js\"></script>\r\n");
      out.write("    <!--  todo JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/todo/jquery.todo.js\"></script>\r\n");
      out.write("	<!--  wave JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/wave/waves.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/admin/js/wave/wave-active.js\"></script>\r\n");
      out.write("    <!-- plugins JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/plugins.js\"></script>\r\n");
      out.write("    <!-- Data Table JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/data-table/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/admin/js/data-table/data-table-act.js\"></script>\r\n");
      out.write("    <!-- main JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <script src=\"resources/admin/js/main.js\"></script>\r\n");
      out.write("	<!-- tawk chat JS\r\n");
      out.write("		============================================ -->\r\n");
      out.write("    <!-- <script src=\"resources/admin/js/tawk-chat.js\"></script> -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
